name: flutter_plugin_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.0.8
author: Tiago Ribeiro <tiagopribeiro.1992@gmail.com>
homepage: https://github.com/CrossPT/flutter_plugin_pdf_viewer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^1.4.1
  path_provider: ^1.6.11
  rxdart: ^0.24.1
  numberpicker: ^1.2.0
  flutter_advanced_networkimage: ^0.7.0

flutter:
  plugin:
    androidPackage: pt.tribeiro.flutter_plugin_pdf_viewer
    pluginClass: FlutterPluginPdfViewerPlugin
